package:
  format-version: "1.0.0"
  name: "reference_apps_pic32cx"
  type: "application"
  status: "production"
  required: false
  version: "1.0.1"

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.20.0"
    - name: "core"
      type: "package"
      version: "v3.14.1"
    - name: "gfx"
      type: "package"
      version: "v3.15.3"
    - name: "wireless_rnbd"
      type: "package"
      version: "v2.0.4"
